name: On Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
  packages: write

jobs:
  determine_app_version:
    name: Determine app version
    if: |
      contains(github.event.pull_request.labels.*.name, 'preview') &&
      (github.event.action != 'labeled' || github.event.label.name == 'preview')
    runs-on: ubuntu-latest
    outputs:
      app_version: ${{ steps.determine_app_version.outputs.app_version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0 # to get tags
      - name: Determine app version
        id: determine_app_version
        run: |
          BASE_VERSION=$(git describe --tags --abbrev=0)
          SHA=${{ github.event.pull_request.head.sha }}
          APP_VERSION=$BASE_VERSION-pr-${{ github.event.pull_request.number }}-${SHA:0:7}
          echo $APP_VERSION
          echo "app_version=$APP_VERSION" >> $GITHUB_OUTPUT
  build_and_push_image:
    name: Image
    needs: determine_app_version
    uses: ./.github/workflows/build-and-push-docker-image.yml
    secrets: inherit
    concurrency:
      group: ${{ github.event.pull_request.head.ref }} # A single build running per branch
      cancel-in-progress: true
    with:
      app_version: ${{ needs.determine_app_version.outputs.app_version }}
      commit_sha: ${{ github.event.pull_request.head.sha }}
      base_sha: ${{ github.event.pull_request.base.sha }}
      cache_tag: pr-${{ github.event.pull_request.number }}
      target: rc
