name: On Release Pull Request Update

on:
  pull_request:
    types: [synchronize, labeled]

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  determine_app_version:
    name: Determine app version
    if: contains(github.event.pull_request.labels.*.name, 'release')
    runs-on: ubuntu-latest
    outputs:
      app_version: ${{ steps.determine_app_version.outputs.app_version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install semver js-yaml @actions/core @actions/github
      - name: Parse level and urgency
        id: parse_level_and_urgency
        run: ./.github/workflows/scripts/parse_pull_request_level_and_urgency.mjs
      - name: Determine app version
        id: determine_app_version
        run: |
          ./.github/workflows/scripts/determine_app_version.mjs \
            --level ${{ steps.parse_level_and_urgency.outputs.level }} \
            --commit-sha ${{ github.event.pull_request.head.sha }}

  build_image:
    name: Image
    needs: determine_app_version
    uses: ./.github/workflows/build-and-push-docker-image.yml
    secrets: inherit
    concurrency:
      group: ${{ github.event.pull_request.head.ref }} # A single build running per branch
      cancel-in-progress: true
    with:
      app_version: v${{ needs.determine_app_version.outputs.app_version }}
      commit_sha: ${{ github.event.pull_request.head.sha }}
      cache_tag: pr-${{ github.event.pull_request.number }}
      target: rc
  push_to_sandbox:
    name: Push to sandbox
    needs: [determine_app_version, build_image]
    uses: ./.github/workflows/push-docker-image-to-ecr-registry.yml
    secrets: inherit
    with:
      environment: sandbox
      source_image: ${{ github.event.repository.name }}:${{ github.event.pull_request.head.sha }}
      destination_image: ${{ github.event.repository.name }}:${{ needs.determine_app_version.outputs.app_version }}
  push_to_production:
    name: Push to production
    needs: [determine_app_version, build_image]
    uses: ./.github/workflows/push-docker-image-to-ecr-registry.yml
    secrets: inherit
    with:
      environment: production
      source_image: ${{ github.event.repository.name }}:${{ github.event.pull_request.head.sha }}
      destination_image: ${{ github.event.repository.name }}:${{ needs.determine_app_version.outputs.app_version }}
  generate_summary:
    name: Generate summary
    needs: [determine_app_version, build_image, push_to_sandbox, push_to_production]
    runs-on: ubuntu-latest
    steps:
      - name: Generate summary
        run: |
          echo "Pull Request for [${{ github.event.pull_request.title }}](https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}) has been updated 🎉" >> $GITHUB_STEP_SUMMARY
          echo "Image tagged **v${{ needs.determine_app_version.outputs.app_version }}** has been built and pushed to the registry." >> $GITHUB_STEP_SUMMARY
