name: On Release Pull Request Update

on:
  pull_request:
    types: [synchronize, labeled]

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  determine_app_version:
    name: Determine app version
    if: contains(github.event.pull_request.labels.*.name, 'release')
    runs-on: ubuntu-latest
    outputs:
      app_version: ${{ steps.determine_app_version.outputs.app_version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install semver js-yaml
      - name: Determine app version
        id: determine_app_version
        uses: actions/github-script@v6
        with:
          result-encoding: string
          retries: 3
          script: |
            const semver = require('semver');
            const yaml = require('js-yaml');
            const fs = require('fs');
            
            const versionFile = yaml.load(fs.readFileSync('version.yaml', 'utf8'));
            const latestVersion = semver.clean(versionFile[':version'][':current']);
            console.log(`Latest release: v${latestVersion}`);
            
            const short_sha = context.payload.pull_request.head.sha.substring(0, 11);
            
            // parse level from labels
            let level;
            context.payload.pull_request.labels.forEach(label => {
              if (label.name.startsWith('level:')) {
                level = label.name.split(':')[1];
              }
            });
            
            console.log('Level:', level);
          
            const bumpedVersion = semver.inc(latestVersion, level);
            const nextVersion = `v${bumpedVersion}-rc-${short_sha}`;
            
            console.log('Next release candidate:', nextVersion);
            
            core.setOutput('app_version', nextVersion)
  build_and_push_image:
    name: Image
    needs: determine_app_version
    uses: ./.github/workflows/build-and-push-docker-image.yml
    secrets: inherit
    concurrency:
      group: ${{ github.event.pull_request.head.ref }} # A single build running per branch
      cancel-in-progress: true
    with:
      app_version: ${{ needs.determine_app_version.outputs.app_version }}
      commit_sha: ${{ github.event.pull_request.head.sha }}
      cache_tag: pr-${{ github.event.pull_request.number }}
      push_to_production: true
      stage: rc
  generate_summary:
    name: Generate summary
    needs: [determine_app_version, build_and_push_image]
    runs-on: ubuntu-latest
    steps:
      - name: Generate summary
        run: |
          echo "Pull Request for [${{ github.event.pull_request.title }}](https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}) has been updated 🎉" >> $GITHUB_STEP_SUMMARY
          echo "Image tagged **${{ needs.determine_app_version.outputs.app_version }}** has been built and pushed to the registry." >> $GITHUB_STEP_SUMMARY
