name: On Tags

on:
  push:
    tags:
      - v*
  workflow_dispatch:

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
  packages: write

jobs:
  determine_app_version:
    name: Determine app version
    runs-on: ubuntu-latest
    outputs:
      app_version: ${{ steps.determine_app_version.outputs.app_version }}
      base_sha: ${{ steps.determine_app_version.outputs.base_sha }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}
          fetch-depth: 0 # to get tags
      - name: Determine app version
        id: determine_app_version
        run: |
          BASE_SHA=$(git rev-parse origin/master)
          APP_VERSION=$(git describe --tags --abbrev=0)
          echo "New app version: $APP_VERSION"
          echo "Base SHA: $BASE_SHA"
          echo "app_version=$APP_VERSION" >> $GITHUB_OUTPUT
          echo "base_sha=$BASE_SHA" >> $GITHUB_OUTPUT
  build_and_push_image:
    name: Image
    needs: determine_app_version
    uses: ./.github/workflows/build-and-push-docker-image.yml
    secrets: inherit
    with:
      app_version: ${{ needs.determine_app_version.outputs.app_version }}
      commit_sha: ${{ github.sha }}
      push_to_production: true
      base_sha: ${{ needs.determine_app_version.outputs.base_sha }}
